name: Build Alioth Kernel (KSU Next)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🧹 Cleanup & Install deps
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /opt/ghc
          sudo apt update
          sudo apt install -y bc build-essential flex bison lld llvm \
          libssl-dev libelf-dev curl git

      - name: ⚙️ Setup Neutron Clang
        run: |
          mkdir clang
          curl -LSs https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman | bash -s -- -S
          echo "$(pwd)/clang/bin" >> $GITHUB_PATH

      - name: 📦 Clone kernel
        run: |
          git clone https://github.com/FunnyDragon2010/kernel_xiaomi_sm8250_KPM -b base kernel

      - name: 🔧 Setup KernelSU Next (LEGACY)
        run: |
          cd kernel
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy

      - name: 🩹 Patch reboot.c (KSU hook)
        run: |
          cd kernel

          sed -i '/SYSCALL_DEFINE4(reboot/i \
#ifdef CONFIG_KSU\n\
extern int ksu_handle_sys_reboot(int magic1, int magic2, unsigned int cmd, void __user **arg);\n\
#endif\n' kernel/reboot.c

          sed -i '/int ret = 0;/a \
#ifdef CONFIG_KSU\n\
\tksu_handle_sys_reboot(magic1, magic2, cmd, &arg);\n\
#endif\n' kernel/reboot.c

      - name: ⚙️ Build kernel
        run: |
          cd kernel

          export ARCH=arm64
          export SUBARCH=arm64
          export PATH="$(pwd)/../clang/bin:$PATH"

          make O=out ARCH=arm64 nethunter_defconfig_alioth

          make -j$(nproc --all) O=out \
            ARCH=arm64 \
            CC=clang \
            LLVM=1 \
            LLVM_IAS=1 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            READELF=llvm-readelf \
            STRIP=llvm-strip

      - name: 📤 Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: Alioth-Kernel-KSU
          path: kernel/out/arch/arm64/boot/Image
                - name: 📦 Clone AnyKernel3
        run: |
          git clone https://github.com/osm0sis/AnyKernel3

      - name: 📦 Copy kernel to AnyKernel3
        run: |
          cp kernel/out/arch/arm64/boot/Image AnyKernel3/

      - name: 🗜 Pack AnyKernel3 zip
        run: |
          cd AnyKernel3
          zip -r9 ../Alioth-Kernel-KSU.zip *

      - name: 📤 Upload AnyKernel3 zip
        uses: actions/upload-artifact@v4
        with:
          name: Alioth-Kernel-KSU-AnyKernel3
          path: Alioth-Kernel-KSU.zip
